/// Flutter icons Spo2
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Spo2
///      fonts:
///       - asset: fonts/Spo2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Spo2 {
  Spo2._();

  static const _kFontFam = 'Spo2';
  static const String? _kFontPkg = null;

  static const IconData spo2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
