/// Flutter icons Temper
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Temper
///      fonts:
///       - asset: fonts/Temper.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Temper {
  Temper._();

  static const _kFontFam = 'Temper';
  static const String? _kFontPkg = null;

  static const IconData temper = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
